#!/bin/bash
# create-fresh-migration.sh - Creates a fresh initial migration from current models
# This script will generate a new migration based on your SQLAlchemy models

set -e

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   Create Fresh Migration from Models                          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Check if running in Docker or locally
if [ -f "/.dockerenv" ]; then
    EXEC_CMD=""
    echo "Running inside Docker container"
else
    EXEC_CMD="docker-compose exec backend"
    echo "Running from host machine"
fi

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

print_info() {
    echo -e "${YELLOW}ℹ️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Step 1: Check current migration status
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 1: Checking current migration status"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
$EXEC_CMD alembic current || print_info "No current migration (this is OK for fresh start)"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 2: Checking existing migrations"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
$EXEC_CMD alembic history | head -20 || print_info "No migrations yet"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 3: Creating new migration from models"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Generate timestamp
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
MIGRATION_NAME="complete_schema_${TIMESTAMP}"

print_info "Generating autogenerated migration: $MIGRATION_NAME"

if $EXEC_CMD alembic revision --autogenerate -m "$MIGRATION_NAME"; then
    print_success "Migration created successfully!"
else
    print_error "Failed to create migration"
    exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 4: Listing new migration files"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ls -lht alembic/versions/ | head -5

echo ""
print_success "Migration created successfully!"
echo ""
print_info "Next steps:"
echo "  1. Review the generated migration file in alembic/versions/"
echo "  2. Apply the migration:"
echo "     ./start.sh migrate"
echo "     OR"
echo "     docker-compose exec backend alembic upgrade head"
echo ""
